version: "2"

services:
  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
      - database
    volumes:
      - "./api:/api"
      - "./docker/nginx:/etc/nginx/conf.d"

  php:
    build: "./docker/php"
    volumes:
      - "./api:/api"
    env_file:
      - .env

  database:
      image: mysql:5.7
      ports:
       - ${DB_EXTERNAL_PORT}:${DB_PORT}
      environment:
       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
       - MYSQL_DATABASE=${DB_DATABASE}
       - MYSQL_USER=${DB_USERNAME}
      volumes:
       - "./docker/mysql/data:/var/lib/mysql"