version: "2"

services:
  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
      - database
    volumes:
      - "./docker/nginx:/etc/nginx/conf.d"
    volumes_from:
      - php

  node:
    build: "./docker/node"
    ports:
      - ${NODE_EXTERNAL_PORT}:${NODE_PORT}

  php:
    build: "./docker/php"
    volumes:
      - "./api:/api"
      - "./docker/supervisor:/etc/supervisor/conf.d/"
      - "./docker/cron/:/etc/cron.d/"
    env_file:
      - .env

  database:
      image: mysql:5.7
      ports:
       - ${DB_EXTERNAL_PORT}:${DB_PORT}
      environment:
       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
       - MYSQL_DATABASE=${DB_DATABASE}
       - MYSQL_USER=${DB_USERNAME}
      volumes:
       - "./docker/mysql/data:/var/lib/mysql"

  redis:
    build: "./docker/redis"
    ports:
      - ${REDIS_EXTERNAL_PORT}:6379
    volumes:
      - "./docker/redis/data:/data"